services:
  mongo:
    image: mongo:latest
    container_name: mongo
    restart: always
    ports:
      - "27017:27017"
    command: ["--replSet", "rs0", "--bind_ip_all"]
    healthcheck:
      test: echo "try { rs.status() } catch (e) { rs.initiate({_id:'rs0',members:[{_id:0,host:'localhost:27017'}]}) }" | mongosh --quiet
      interval: 10s
      start_period: 5s
    volumes:
      - mongodb_data:/data/db
      - ./mongod.conf:/etc/mongo/mongod.conf:ro # Optional: Uncomment and create mongod.conf if you need custom configuration
    networks:
      - docker_services_network

volumes:
  mongodb_data:
    name: mongodb_data

networks:
  docker_services_network:
    name: docker_services_network
    external: true